spring:
  application:
    name: ActivityReccomender
  meteo:
    token: NoKeyNeededForOpenMeteoNonCommercialUse
    hostname: https://api.open-meteo.com
  geoApify:
    key: ${geoKey}
    hostname: https://api.geoapify.com

logging:
  level:
    org.springframework.web.reactive.function.client: DEBUG
    reactor.netty.http.client: DEBUG
