spring:
  application:
    name: ActivityReccomender
  meteo:
    token: NoKeyNeededForOpenMeteoNonCommercialUse
    hostname: https://api.open-meteo.com
  geoApify:
    key: ${geoKey}
    hostname: https://api.geoapify.com
  openai:
    token: ${openAiToken}

openai:
  timeouts:
    read: 8000
    connect: 2000

resilience:
  timelimiter:
    instances:
      openmeteo-api:
        timeoutDuration: 5s
      geoapify-api:
        timeoutDuration: 5s
  circuitbreaker:
    instances:
      geoapify-api:
        sliding-window-size: 10
        minimum-number-of-calls: 5
        failure-rate-threshold: 50
        slow-call-duration-threshold: 2s
        wait-duration-in-open-state: 30s
        permitted-number-of-calls-in-half-open-state: 3
        automatic-transition-from-open-to-half-open-enabled: true

        record-exceptions:
          - java.net.ConnectException
          - java.net.SocketTimeoutException
          - java.io.IOException
          - java.lang.RuntimeException
        ignore-exceptions:
          - java.lang.IllegalArgumentException
      openmeteo-api:
        sliding-window-size: 10
        minimum-number-of-calls: 5
        failure-rate-threshold: 50
        slow-call-duration-threshold: 2s
        wait-duration-in-open-state: 30s
        permitted-number-of-calls-in-half-open-state: 3
        automatic-transition-from-open-to-half-open-enabled: true

        record-exceptions:
          - java.net.ConnectException
          - java.net.SocketTimeoutException
          - java.io.IOException
          - java.lang.RuntimeException
        ignore-exceptions:
          - java.lang.IllegalArgumentException

logging:
  level:
    io.github.resilience4j: TRACE
    org.springframework.cloud.circuitbreaker: TRACE
    org.springframework.cloud.client.circuitbreaker: TRACE
    reactor.core.publisher: DEBUG
    org.springframework.web.reactive.function.client: DEBUG
    reactor.netty.http.client: DEBUG
